### ISSUE TITLE
Where is dataset?

### ISSUE THREAD

**Issue by leopeng1995** [samuelzhouhe/poseGuidedImgGeneration#1]
ATT.
Thx~ :-)

**Comment by coeusguo** [comment]
Hi Leo,
The dataset can be found here:
http://mmlab.ie.cuhk.edu.hk/projects/DeepFashion/InShopRetrieval.html
which is the official website of deep fashion dataset.

**Comment by leopeng1995** [comment]
Thanks for your help. I will try it. 👍

**Comment by samuelzhouhe** [comment]
@leopeng1995 I've updated the README. After downloading the dataset, you may wish to download the file of body keypoints prepared by us, before running the code.

Thanks.
