### ISSUE TITLE
what should i do after i have download the deepfashion dataset

### ISSUE THREAD

**Issue by MandyMo** [samuelzhouhe/poseGuidedImgGeneration#2]
what should i do after i have download the deep-fashion dataset

Is there exist extra data process out of your github code.

**Comment by wangsen1312** [comment]
@MandyMo  Any update?

**Comment by samuelzhouhe** [comment]
@MandyMo @wangsen1312 
I've updated the README.md with more detailed instructions.
If you have downloaded the dataset DeepFashion, please follow the instruction in README to download the files of body keypoints prepared by us, and then run the code.
Thanks.

**Comment by wangsen1312** [comment]
@samuelzhouhe  Yes  it is much more clear now~  Thank you very much~
