### ISSUE TITLE
Error when run demo using pre-trained model

### ISSUE THREAD

**Issue by codaibk** [samuelzhouhe/poseGuidedImgGeneration#6]
Hi, I tried to run demo with pre-train model following your guide using this command `python3 demo.py `but it get this error : 
```
File "/home/vipgpu/trang/poseGuidedImgGeneration/model_all.py", line 67, in __setup
    .reshape(cfg.BATCH_SIZE, W, H, 768, name = 'reshape'))
File "/home/vipgpu/trang/poseGuidedImgGeneration/network.py", line 20, in wrapper
    output = layer(self, ipt, *args, **kwargs)
TypeError: reshape() got an unexpected keyword argument 'name'
```
do you know how to fix it?
Thanks

**Comment by bandontseng** [comment]
Do you use python2?
I encountered the similar problem with python2. After switched to python3, I could run it without any problem.

**Comment by codaibk** [comment]
Thanks but I installed python 3.5 and still get error

**Comment by codaibk** [comment]
Ah, It works now ^^
