### ISSUE TITLE
Where can I find 'model.h5' file?

### ISSUE THREAD

**Issue by ZhangYK124** [samuelzhouhe/poseGuidedImgGeneration#7]
Hello, I have a question to ask.
in read_keypoint.py
weights_path = "./keras_Realtime_Multi-Person_Pose_Estimation/model/keras/model.h5"

Do you have 'model.h5'？

**Comment by samuelzhouhe** [comment]
Hi, we did not upload the keypoint detection model, but we've uploaded the end-product of keypoint detection instead. Please download all the keypoints https://drive.google.com/file/d/1DwRPXCyVYBmtGa0hO3JlYkrD709s6zca/view?usp=sharing here.
